### ISSUE TITLE
Agregar reglas sobre las reincidencias

### ISSUE THREAD

**Issue by matiasalbacetti** [matiasalbacetti/LarrataFiles#1]
Si a alguien lo echan a cada rato tiene q ser más grave la pena

**Comment by matiasferrerovilas** [comment]
si se lo echa en 1 semana mas de 2 veces, su pena se duplica, algo asi?

**Comment by matiasalbacetti** [comment]
@matiasferrerovilas no me convence, tendría que ser algo a nivel mensual, bimensual, semestral o anual, más detallado

**Comment by matiasferrerovilas** [comment]
Semanal seria lo mejor, que tenemos la memoria mas fresca, porque si es mensual hay que llevar un tipo de conteo o revisar los mensajes de 1 mes y ver cuantas veces se lo saco a uno y eso costaria mucho.

**Comment by matiasalbacetti** [comment]
mmm si es semanal creo q no vale la pena, es muy poco...
en fin, definanlo uds

**Comment by matiasalbacetti** [comment]
@Mathy977 esto no es un bug, es una mejora

**Comment by matiasferrerovilas** [comment]
Mensual deberia ser al final,  si en un mes se lo echo mas de 3 veces, las penalizaciones correspondientes al mes siguientes se le suimaria 3(tres) dias mas.
