### ISSUE TITLE
Artículo para obligar a asistir a salidas

### ISSUE THREAD

**Issue by matiasalbacetti** [matiasalbacetti/LarrataFiles#14]
Estaría bueno algo que, por ejemplo, imponga sanción si alguien rechaza 7 salidas seguidas. Tipo de sanción y número y tipo de salidas a definir

**Comment by matiasalbacetti** [comment]
Uds van a llevar el puntaje d todos?

**Comment by matiasferrerovilas** [comment]
Podriamos Tener un hashtag como tenemos con Vacaciones y FaltasOrtografia

**Comment by matiasferrerovilas** [comment]
La Administración evaluó y aprueba esta solicitud
