### ISSUE TITLE
Prueba de concepto de nueva plataforma (Telegram)

### ISSUE THREAD

**Issue by EduardoYujra** [matiasalbacetti/LarrataFiles#15]
Se puede probar la herramienta Telegram y ver sus  pros y sus contras.
Ya que a mi parecer es una plataforma mejor y con más funcionalidades que su competidora (WhatsApp)

**Comment by matiasferrerovilas** [comment]
Me gusta, podriamos probarlo

**Comment by matiasferrerovilas** [comment]
LarrataGO (Telegram)
https://t.me/joinchat/AAAAAFX5_B-YXrDZx9-pEg

**Comment by Mathy977** [comment]
What's app nos basta y sobra a mí parecer

**Comment by Mathy977** [comment]
**RECHAZADO,**
 Resulta inviable que todos los agentes migren de plataforma.
