### ISSUE TITLE
Penalizacion por Emojis

### ISSUE THREAD

**Issue by NicolasRamis** [matiasalbacetti/LarrataFiles#22]
Propongo penalizar a las personas (como Matias Nicolas Notario) quienes usan emojis o simbolos como " (? " innecesariamente o, al menos cuando no tiene nada que ver con lo que está escribiendo.
Ejemplo: Alguien propone hacer algo y contestan "Voy 😱"

Gracias

**Comment by matiasferrerovilas** [comment]
No lo veo necesario

**Comment by matiasferrerovilas** [comment]
No aporta mucho esta "regla", me parece que seria limitar a todos demasiado con eso, y seria muy subjetivo.
