### ISSUE TITLE
Regla que penalice la no lectura del reglamento

### ISSUE THREAD

**Issue by matiasalbacetti** [matiasalbacetti/LarrataFiles#23]
una regla que castigue a quien demuestre no haber leído el reglamento

**Comment by matiasferrerovilas** [comment]
no lo veo necesario en todo caso  si no lo leen y despues se los echa  que se jodan

**Comment by Mathy977** [comment]
Opino igual que Ferrer. Uno no esta obligado a leer las leyes pero si queres saber tus derechos y obligaciones, lo tenes que hacer
