### ISSUE TITLE
Automatizacion de alertas de cantidad de salidas

### ISSUE THREAD

**Issue by EduardoYujra** [matiasalbacetti/LarrataFiles#24]
Los supremos podrían desarrollar una web api que detecte o de alguna forma identifique y lleve un tracking de las personas que no van a las salidas y llegado un punto de tener pocos "puntos" enviar una alerta por mail sobre cuantos puntos le quedan.

**Comment by matiasferrerovilas** [comment]
Investigare el tema, esta muy bueno si tenes idea avisa

**Comment by EduardoYujra** [comment]
Mi idea es hacer una app service que lea una planilla de Google spread sheet donde estaríamos todos nuestros nombres y la cantidad de puntos por las salidas.

**Comment by matiasalbacetti** [comment]
Vos no "hacés" un App Service. El App Service es cómo hostearías el programita que querés hacer.

La restricción de esta propuesta es que Whatsapp no tiene API, y nuestro canal de comunicación es Whatsapp.

**Comment by EduardoYujra** [comment]
No es necesario WhatsApp, en la juntada misma se hace la baja de puntos o suma mediante una app de Android

**Comment by matiasferrerovilas** [comment]
Vos decis entonces, que  hagamos una app y en ella cargar los puntos, y que ella guarde en una planilla de  google y que por ahi le avise a los usuarios que tienen 0?

**Comment by matiasalbacetti** [comment]
No es necesaria una app... Lo que yo entendí que sugirió es que el conteo de puntos se lleve en una planilla y que un programita automático avise cuando alguien tiene menos de X puntos... Pero eso va a requerir que el conteo se lleve en un lugar distinto al grupo de Whatsapp

**Comment by EduardoYujra** [comment]
El conteo no es necesario llevarlo, de hecho para eso lo propuse para no tener que contar. Por ejemplo organizamos una salida y la salida se concreta con todos menos por ejemplo Cris, entonces cuando estemos en la salida por ejemplo hormiga negra, en ese momento cuando estemos en hormiga negra se usaría la app Android indicando quien no está presente en CHN

**Comment by matiasferrerovilas** [comment]
Y pero ponele que uno llegue a 0, por wpp le tendira que avisar, y eso ya necesitas permisos o credenciales o lo que sea. Salvo que le mandes por mail a todos

**Comment by EduardoYujra** [comment]
Tendríamos que definir como avisar, ya desde WhatsApp no es posible o demasiado complicado.

**Comment by matiasferrerovilas** [comment]
Creo que deberia mandarse por mail a todos y listo, porque sino no se

**Comment by Mathy977** [comment]
Me parece genial la idea. Hay que buscar una forma de implementarlo

**Comment by NicolasRamis** [comment]
Alguna novedad sobre esto?

**Comment by EduardoYujraT** [comment]
Primero tenemos que armar la lista de mails luego veremos como implementar una solución a este issue.

**Comment by NicolasRamis** [comment]
Podrian hacer dicho listado. No es muy complejo ni se tardaría mucho.

**Comment by EduardoYujraT** [comment]
se cierra el issue por falta de aplicación
