### ISSUE TITLE
Que una salida a un lugar a más de 200km de CABA se considere viaje

### ISSUE THREAD

**Issue by matiasalbacetti** [matiasalbacetti/LarrataFiles#25]
Lo que sugiero es ampliar la categoría "viajes" de salidas.
Actualmente, si vamos a la costa y volvemos en el día, eso no se consideraría un viaje pues no permanecemos 24hs alejados de CABA.
Yo creo que si vamos a un lugar muy lejano debería considerarse un viaje sin importar la duración.

**Comment by Mathy977** [comment]
Implementado en el commit 71e5642dd7702b17519af8e23e3e29c887c96653.
