### ISSUE TITLE
Penalización por no tener interacción en LarrataFiles

### ISSUE THREAD

**Issue by EduardoYujra** [matiasalbacetti/LarrataFiles#26]
Propongo una medida, que avise o sancione a quienes no tienen una participación activa en LarrataFiles.
Por ejemplo los miembros del grupo deberían tener al menos algún comentario en el mes en cualquier issue que se cree. 
De no ser así, la opinión o palabra de dicho miembro que no participe en LarrataFiles no tendrá impacto alguno o no se lo tomara en cuenta en decisión importantes siempre y cuando los supremos pidan o necesiten la opinión del resto del grupo.

**Comment by Mathy977** [comment]
No me parece necesario, cada agte. esta en su derecho de participar o no en LarrataFiles. Queda en ellos tener participacion en las reglas que luego lo van a regir o no.
