### ISSUE TITLE
Implementación de app para dividir gastos

### ISSUE THREAD

**Issue by EduardoYujra** [matiasalbacetti/LarrataFiles#27]
Seria bueno hacer una prueba de concepto de esta app para el grupo para simplificar las cosas a pagar en las salidas

@matiasalbacetti @Mathy977 @matiasferrerovilas 

https://www.youtube.com/watch?v=EfyoqStTAjs

https://play.google.com/store/apps/details?id=com.Splitwise.SplitwiseMobile&hl=es

**Comment by Mathy977** [comment]
Creo que este tema excede al alcance de la juridicción del Grupo de wpp. Quizas se podria charlar en el mismo pero no encuentro necesario una reglamentación
