### ISSUE TITLE
Agregar apodo a corsi

### ISSUE THREAD

**Issue by Mathy977** [matiasalbacetti/LarrataFiles#30]
Epdc

**Comment by NicolasRamis** [comment]
Opino que no es de relevancia y desde mi punto de vista, daría de baja la issue.

**Comment by EduardoYujraT** [comment]
opino lo mismo.
@Mathy977, yo propongo cerrar el issue sin el apodo

**Comment by NicolasRamis** [comment]
Concuerdo.

**Comment by Mathy977** [comment]
Acordado
