### ISSUE TITLE
Prohibición de ingresar a Cris 

### ISSUE THREAD

**Issue by MatiasNicoN** [matiasalbacetti/LarrataFiles#32]
¿ Y si hacemos una pauta que haga que mas alla de quien este en el poder del grupo no pueda agregar a cris o a algun fantasma ? Tambien, en el caso de que lo agregue algun admin de otra administracion, si tiene el poder y se pasa por alto esto, sea expulsado por tiempo "indefinido" por el 2do admin ? Asi bien opresor.

Tambien apoyo la no mención del sujeto en cuestion asi como a "J"

#NoMasFalopasEnElGrupo

**Comment by matiasalbacetti** [comment]
Apoyo

**Comment by GabrielGatica** [comment]
No me parece, no hizo nada malo para que hagan esto

**Comment by kev2g** [comment]
Apoyo la moción de reingresar a Marquitos

**Comment by NicolasRamis** [comment]
No apoyo. Apoyo la opinion de kevin

**Comment by MatiasNicoN** [comment]
Con marquitos no tengo drama, puede aportar falopa al grupo, pero la de verdad (? jaja

**Comment by EduardoYujraT** [comment]
Si quieren que marquitos reingrese al grupo tienen que crear un nuevo issue y este será tratado por los administradores.

Por el tema de la prohibicion de ingresar a Cris si nadie esta interesado más en el tema entonces se cerrara el issue.

@Mathy977
