### ISSUE TITLE
Base de correos

### ISSUE THREAD

**Issue by NicolasRamis** [matiasalbacetti/LarrataFiles#33]
De igual manera que están documentados los DNI y fechas de cumpleaños de cada "agente", creo que seria de utilidad agregar las direcciones de correo de cada uno. En caso de que se creara un documento compartido, se utilizarian esos correos.

**Comment by EduardoYujra** [comment]
Se encuentra en proceso y proximo a su finalización.

**Comment by EduardoYujraT** [comment]
Issue resuelto

https://docs.google.com/spreadsheets/d/1Bwbe1EAwp1qoNmNu-IbUQQhjg2isTl36anaXgynVXuQ/edit#gid=0

**Comment by matiasalbacetti** [comment]
Considero que la base de correos, al igual que los datos útiles y todo lo que ya tenemos, debería estar en el reglamento.
