### ISSUE TITLE
Actualizar reglamento. 

### ISSUE THREAD

**Issue by matiasalbacetti** [matiasalbacetti/LarrataFiles#35]
Nueva administración.
Reglas que van y que no van.

**Comment by kev2g** [comment]
Cuales serían estás reglas? Probablemente esto trascienda a la administración interina, pero estaría bueno dejarlo aclarado así la próxima administración puede resolverlo apenas asuma. Leyendo el reglamento actual solo se me ocurre actualizar nombres, firmas e iconografía, pero puede ser que se me esté pasando algo...

**Comment by saantiagovera** [comment]
Dado a la verificacion y conformidad de las reglas, se cierra issue
