### ISSUE TITLE
Repositorio de CBUs, alias, cuentas de Todo Pago, etc + Centralizar info

### ISSUE THREAD

**Issue by matiasalbacetti** [matiasalbacetti/LarrataFiles#39]
Tener en un lugar accesible para todos los miembros del grupo los datos necesarios para realizarle pagos vía medios digitales a los agentes.

Sugiero CBU o alias de cuenta bancaria y alias de Todo Pago

**Comment by matiasalbacetti** [comment]
Habría que dejar la info de los agentes en un sólo lugar, si es en el reglamento que esté solamente ahí, y si se va a poner en un doc. a parte, q en el reglamento esté el link a ese doc.

**Comment by EduardoYujraT** [comment]
vamos a estar haciendo un relevamiento de la información durante este fin de semana además de centralizar la información

**Comment by EduardoYujraT** [comment]
Esta la informacion de casi todos los agentes con la excepcion de Julian Corsi.

**Comment by EduardoYujraT** [comment]
Se esta resolviendo el tema de como mostrar la informacion bancaria

**Comment by kev2g** [comment]
> Se esta resolviendo el tema de como mostrar la informacion bancaria

Creo que el lugar de más fácil acceso para todos es el reglamento, a menos que se esté trabajando en algo más elaborado.

**Comment by saantiagovera** [comment]
Dado a que actualmente al momento de pago, agentes verifican sus medios de pago y que en un apartado de github ya hay informacion bancaria, se cierra issue
