### ISSUE TITLE
Nueva regla por advertencia sobre comportamiento no aceptado en el grupo

### ISSUE THREAD

**Issue by EduardoYujraT** [matiasalbacetti/LarrataFiles#41]
La idea es crear una regla donde se implemente una advertencia sobre conducta fuera de lugar con el motivo de que el agente se tranquilice y si sigue con la misma actitud proceder a una expulsion del grupo durante 5min (ban temporal) pero antes de la expulsion dar un mensaje de notificiacion sobre los motivos.

Estaria a definir como ejecutar esta advertencia es decir si los supremos actuen de oficio o someterlo a votacion o alguno otra forma.

**Comment by matiasalbacetti** [comment]
Propongo la metodología de 3 strikes en período de tiempo

**Comment by EduardoYujraT** [comment]
se procede a la redacción de la nueva regla, sujeta a modificaciones para ir ajustando su mejor aplicación

**Comment by kev2g** [comment]
Apoyo esta idea. Desde hace tiempo viene siendo necesario. Creo que ya habían estado trabajando en algo...? 

> se procede a la redacción de la nueva regla, sujeta a modificaciones para ir ajustando su mejor aplicación

Perdón, pero soy nuevo en esto de GitHub, y no se donde ver tests, o como modificar los archivos. Si están de acuerdo abría que cerrar este issue.

**Comment by saantiagovera** [comment]
Cierro issue dado a que ya esta dicho articulo en el reglamento
