### ISSUE TITLE
Quitar del reglamento los artículos que no se tienen en cuenta actualmente

### ISSUE THREAD

**Issue by matiasalbacetti** [matiasalbacetti/LarrataFiles#42]

**Comment by corsijulian** [comment]
Chicos le podríamos dar prioridad a este tema? Gracias.

**Comment by matiasferrerovilas** [comment]
cuales no se tienen en cuenta actualmente?

**Comment by kev2g** [comment]
> cuales no se tienen en cuenta actualmente?

Same, como había mencionado en #35 habría que especificar. Gracias

**Comment by saantiagovera** [comment]
Se cierra issue dado a que se resolvio
