### ISSUE TITLE
Elecciones para cambio de administrador

### ISSUE THREAD

**Issue by corsijulian** [matiasalbacetti/LarrataFiles#44]
Solicito que la administración organice unas elecciones formalizadas y organizadas para que los integrantes del grupo tengan la posibilidad de elegir un nuevo administrador o que la fórmula actual siga al mando del poder.
Creo que sería necesario que sea en las próximas semanas ya que hay un gran descontento por parte de varios integrantes del grupo.

Espero su pronta respuesta, saludos.

**Comment by kev2g** [comment]
Es bueno ver que ya se había creado un issue para esto. Lo utilizaré para dejar los detalles pertinentes a la próxima elección y pedir correcciones/ideas/opiniones en caso de haberlas.

Propóngase: las elecciones para la siguiente administración en la fecha del Domingo 04/08/2019, de 13 a 16hs. 
Candidatos: podrán presentar sus candidaturas todos los miembros del grupo hasta el día Sabado 03/08/2019 a las 18hs. Desde ese momento hasta la votación, se llevará a cabo el "Periodo de Campaña".
Plataforma de votación propuesta: https://www.adoodle.org
Es la mejor plataforma que encontré para esta votación. El voto es secreto. Se le envía un mail a cada agente (tenemos una base de mails). Solo se permite votar una vez. Antes de la votación voy a hacer un tutorial con imágenes, dado que el mail que se envía es automático y en ingles, y no quiero que haya confusiones sobre como votar. Además, después de votar, todos pueden seguir la votación en vivo. Si alguien conoce una plataforma mejor, por favor propongala. 
Algunas notas: 
- La resolución de Issues pendientes al momento de la votación pasará a ser responsabilidad de la siguiente administración. Lo digo porque  ademas de esta votación. estoy planeando abrir un issue con reformas para democratizar un poco el grupo, pero estas reformas empezarían en la gestión interina y terminarían en la siguiente gestión, si hay voluntad de hacerlo.
- La gestión interina llevó a cabo investigaciones sobre violaciones al reglamento desde mediados de julio hasta el día de la fecha. Para garantizar la plena participación del sufragio, las sanciones no se llevaran a cabo por esta administración, sino por la siguiente. Se pasará junto con el admin un informe con los resultados de esta investigación y recomendaciones sobre las sanciones a ejecutarse.

Los dos primeros en votos pasan a ser los nuevos administradores. 

El traspaso del admin será inmediato. 

Escucho opiniones si las hay.

**Comment by kev2g** [comment]
Si están todos de acuerdo, procedo a anunciar las elecciones.

**Comment by saantiagovera** [comment]
Dada las elecciones celebradas, procedo a concluir issue
