### ISSUE TITLE
Cumpleaños

### ISSUE THREAD

**Issue by matiasferrerovilas** [matiasalbacetti/LarrataFiles#45]
Ponganlo como quieran regla o actividad que deben cumplir, pero que en los cumpleaños los administradores deberian mandar un comunicado felicitando a la persona que cumple años.

**Comment by corsijulian** [comment]
Me agrada la idea. Creo que sería un buen aporte para que nadie se olvide de saludar al cumpleañero también. Ojalá no tarden tanto en implementarlo como todo lo demás.

**Comment by matiasferrerovilas** [comment]
Antes se hacia esto..

**Comment by matiasalbacetti** [comment]
Debería ser a las 23:50 para que se sepa quién se acordó genuinamente y quién necesitó que le avisen

**Comment by kev2g** [comment]
Apoyo esto. Si nadie está en contra, creo que habría que redactarlo e implementarlo desde ahora en el reglamento. No lo hago yo porque como comenté anteriormente, soy nuevo en esto de GitHub y todavía no tengo idea de como modificar archivos, etc. 

> Debería ser a las 23:50 para que se sepa quién se acordó genuinamente y quién necesitó que le avisen

Estaría bueno eso, pero si algo no enseña Gabot es que no es lo mismo un besito de buenos días a las 6 am que a las 10 am.

**Comment by saantiagovera** [comment]
Se agrego en uno de los anexos lo del saludo a los cumpleañeros. Se cierra issue
