### ISSUE TITLE
Reforma: Proyecto de Democratización

### ISSUE THREAD

**Issue by kev2g** [matiasalbacetti/LarrataFiles#46]
Este issue es para proponer algunas reformas con el objetivo de hacer una transición hacia un sistema un poco más democrático en este grupo. Como lo mencioné en el issue #44 , la reforma se propone durante la gestión interina, pero se termina durante la próxima gestión, por lo que en gran parte depende de la voluntad de la próxima administración y de las siguientes elecciones. 

Las reformas que se proponen son principalmente las siguientes 3:
- **Que los administradores no estén exentos de las reglas.** Si un admin comete un impropio, el otro lo tiene que expulsar. Si los dos violan el reglamento, tienen que pasar el admin a alguien de forma provisoria (o algo así) y salir del grupo. Es esencial que los miembros del grupo le hagan notar la falta al administrador.
- **Que se los miembros puedan convocar a elecciones con una mayoría de votos.** Si los miembros reúnen una mayoría de votos, ya sea por WhatsApp o cualquier otra plataforma legitima, se les permita llamar a votación.
- **Periodicidad de las elecciones.** Queda claro que pasado cierto tiempo, el grupo se harta de los admin y los admin se hartan del grupo, lo que lleva a la acefalía. Por eso, tendríamos una gestión más eficaz si esta se renovara constantemente. Diría con un periodo de 3 o 4 meses.

El mayor inconveniente con estas reformas es que están atadas a la iniciativa de reclamo por parte de los miembros del grupo y del poder de negociación que estos junten. En caso de no cumplir las demandas los admins, la única herramienta que tendrían sería la creación de 
un nuevo grupo y el éxodo a este mismo.

Escucho opiniones/ideas/correcciones

**Comment by kev2g** [comment]
Si están todos de acuerdo, entonces procedo a cerrar el issue y anunciar las elecciones.

**Comment by saantiagovera** [comment]
Me parece una buena idea. De hecho, en mi opinion, se deberia votar cada 6 meses, aplicar elecciones en caso de que peligre la republica (simplemente teniendo mas del 50% del grupo en quorum)

**Comment by saantiagovera** [comment]
Se agrego Anexo 8 en el Reglamento. El mismo estipula plazo de gobierno de 6 meses, posibilidad de llamar a elecciones si los agentes ven que se fue todo al chori. Se elimina superpoderes para administradores. Saludos!
