### ISSUE TITLE
Avisos en Larrata

### ISSUE THREAD

**Issue by NicolasRamis** [matiasalbacetti/LarrataFiles#48]
Por mas que el grupo "Casino GO" esté "asociado" a Larrata, opino que las asistencias o inasistencias deberian informarse unicamente en el ultimo grupo mencionado ya que, de avisarse en "Casino GO" solamente 6 agentes estarían al tanto.

**Comment by kev2g** [comment]
+1

**Comment by saantiagovera** [comment]
Ya fue realizada la modificación, se cierra issue
