### ISSUE TITLE
Cronograma de días de cursada 

### ISSUE THREAD

**Issue by matiasalbacetti** [matiasalbacetti/LarrataFiles#50]
Que los agentes puedan informar los días de la semana en que no están disponibles para asistir a salidas, con el fin de que no tengan que rechazar repetitivamente por este motivo las invitaciones.

**Comment by matiasalbacetti** [comment]
Pensé que esta administración respondía rápido

**Comment by saantiagovera** [comment]
Buenas tardes! 

Es buena la propuesta, aunque habría que consultar agente por agente y puede llevar su tiempo

**Comment by matiasalbacetti** [comment]
Para eso están

**Comment by matiasalbacetti** [comment]
Para eso el pueblo los votó, asuman el gobierno

**Comment by saantiagovera** [comment]
Lo hemos asumido y en tan solo 15 dias se hizo más que en lo últimos meses (me extraña que usted no lo sepa). Se tendrá en cuenta su sugerencia y se evaluará con el admin Notario en el momento pertinente. 

Saluda atte 
La Administración

**Comment by saantiagovera** [comment]
La administración considera inviable a corto plazo la propuesta, por lo cual cierra caso!
