### ISSUE TITLE
Exterminar ambigüedades del artículo 3

### ISSUE THREAD

**Issue by matiasalbacetti** [matiasalbacetti/LarrataFiles#51]
La redacción del artículo 3 no contempla la totalidad de situaciones que pueden producirse. Propongo que la administración reformule el mismo para no dejar lugar a vacíos legales o situaciones sujetas a interpretación a futuro.

**Comment by saantiagovera** [comment]
Se tratará de hacer ciertas modificaciones a este articulo y otros. Se estima antes del 6/2020 generarlo. Se propondrá y se hará consulta popular para modificar los articulos necesarios.
