### ISSUE TITLE
Reglamentar formato de respuesta a invitaciones

### ISSUE THREAD

**Issue by matiasalbacetti** [matiasalbacetti/LarrataFiles#53]
Creación de una regla que obligue a los agentes a anotarse en un listado como forma de respuesta a cualquier invitación.
Analizar si se penaliza o no otro tipo de respuesta.
Formato sugerido:
*[Fecha/Hora] - [Referencia a la salida]*
1) Agente1
2) Agente2
...
N) AgenteN

**Comment by saantiagovera** [comment]
Me agrada la idea, fomenta el orden. En cuanto a la sancion, quizas con 1 dia esta bien.
